Trying to implement a class based model of each node.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [130]:
class Node:
    def __init__(self, l, num_packets, i):
        self.i=i
        self.l=l
        self.packet_id=0
        self.num_packets=num_packets
        self.inter_arrival_times=np.random.exponential(1/l, (num_packets))
        self.arrival_times=np.cumsum(self.inter_arrival_times)
        self.timestamps=np.ceil(self.arrival_times)
        for j in range(len(self.timestamps)):
            if(j>0):
                if(self.timestamps[j]==self.timestamps[j-1]):
                    for k in range(j, len(self.timestamps)):
                        self.timestamps[k]+=1
        self.max_time=np.amax(self.timestamps)
        self.successes=0
        self.collision=0 # randomly choose one out of 2^(collision) consecutive slots
    def push(t_start, backoff):
        
            
        

In [118]:
mynodes=[Node(0.125, 10, i) for i in range(4)]
max_time=np.min([mynodes[i].max_time for i in range(4)])

In [119]:
mynodes[1].timestamps

array([ 3.,  5.,  8., 10., 29., 43., 44., 87., 91., 97.])

In [120]:

for t in range(int(max_time)+1):
    temp=[[]]*(int(max_time)+1)
    for node in mynodes:
        if t in node.timestamps:
            print(node.i, t)

(0, 3)
(1, 3)
(3, 4)
(1, 5)
(0, 6)
(2, 6)
(2, 7)
(1, 8)
(1, 10)
(3, 13)
(0, 23)
(2, 23)
(3, 24)
(2, 25)
(0, 29)
(1, 29)
(0, 36)
(3, 38)
(0, 39)
(2, 39)
(1, 43)
(1, 44)
(0, 47)
(0, 48)
(0, 49)
(3, 53)
(3, 54)
(3, 57)
(3, 63)
(3, 83)
(3, 84)


In [134]:
tput=[]
input_G=np.arange(0.1, 5, 0.1)
mynodes=[Node(G/4, 10, i) for i in range(4)]
max_time=np.min([mynodes[i].max_time for i in range(4)])
for t in range(int(max_time)+1):
    actives=[]
    for node in mynodes:
        if t in node.timestamps:
            actives.append(node)
    if(len(actives)==1):
        actives[0].successes+=1
        actives[0].collision=0
    elif(len(actives)>1):
        print("collision between ")
        temp=[]
        for active in actives:
            print(active.i)
            active.collision+=1
            backoff=np.random.randint(0, int(2**(active.collision))-1)
            temp.append(backoff)
        print(temp)
total_successes=0
for node in mynodes:
    total_successes+=node.successes


collision between 
0
1
2
[0, 0, 0]
collision between 
0
1
2
3
[0, 2, 0, 0]
collision between 
0
1
3
[1, 4, 0]
collision between 
0
2
3
[4, 1, 3]
collision between 
0
1
2
3
[17, 13, 9, 12]
collision between 
0
1
2
3
[17, 23, 9, 6]
collision between 
0
1
[4, 29]
collision between 
0
1
[110, 4]
collision between 
0
1
[258, 74]
collision between 
0
1
2
3
[36, 196, 28, 19]


In [62]:
mynodes[1].timestamps

array([ 5., 15., 16., 19., 20., 21., 23., 26., 30., 36.])

array([ 4.3168467 , 14.50984872, 14.51076377, 17.39086581, 18.66054257,
       19.43561355, 21.08453062, 24.47634247, 28.51996281, 34.71164101])

In [44]:
mynodes[1].timestamps

array([ 4.,  5., 21., 25., 30., 40., 47., 48., 49., 58.])